version: '3'

services:
  db:
    image: mysql:5.7
    environment: 
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: db_test
    ports: 
      - 3306:3306
  web:
    build: .
    depends_on: 
      - db
    volumes: 
      - ./php/:/var/www/html/
    ports: 
      - 8000:80
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports: 
      - 8100:80
    links: 
      - db:db
    environment:
      MYSQL_ROOT_PASSWORD: 1234